config/routes.rb
Mistura::Application.routes.draw do
  root :to => "rests#index"
  resources :rests

end

app/models/rest.rb
class Rest < ActiveRecord::Base
  attr_accessible :nombre, :direccion, :lat, :lng
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rests_controller.rb
class RestsController < ApplicationController

  def index
    @restaurantes = Rest.find(:all)
  end

  def show
      #@restaurantes = Rest.find(params[:id])
      @restaurantes = Rest.find(:all)
  end

def new
   @restaurantes = Rest.new
end

  def create
    @restaurantes = Rest.new(params[:rest])
    if @restaurantes.save
      redirect_to @restaurantes
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rests_helper.rb
module RestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand">Mistura</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to 'Inicio', rests_path %></li>
              <li class="active"><%= link_to 'Registro de Restaurantes', new_rest_path %></li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<%= yield %>

</body>
</html>

app/views/rests/create.html.erb
<h1>Rests#create</h1>
<p>Find me in app/views/rests/create.html.erb</p>

app/views/rests/destroy.html.erb
<h1>Rests#destroy</h1>
<p>Find me in app/views/rests/destroy.html.erb</p>

app/views/rests/edit.html.erb
<h1>Rests#edit</h1>
<p>Find me in app/views/rests/edit.html.erb</p>

app/views/rests/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>GMaps &mdash; Markers</title>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <%= javascript_include_tag 'gmap' %>
  <%= stylesheet_link_tag 'bootstrap' %>
  <%= stylesheet_link_tag 'examples' %>

  <script type="text/javascript">
    var map;
    $(document).ready(function(){
      map = new GMaps({
        div: '#map',
        lat: -12.043333,
        lng: -77.028333
      });
      
      <% @restaurantes.each do |i| %>
      map.addMarker({
        lat: <%= i.lat %>,
        lng: <%= i.lng %>,
        title: "<%= i.nombre %>",
        infoWindow: {
          content: "<%= i.nombre %> <p><p> <%= i.direccion %>"
        }
      });

      <% end %>
    });
  </script>
</head>
<body>
  <div id="header">
    <h2>Los Restaurantes de Mistura</h2>
  </div>
  <div id="body">
    <h3>Restaurantes</h3>
    <div class="row">
      <div class="span11">
        <div class="popin">
          <div id="map"></div>
        </div>
      </div>
      <div class="span6">
        <p><strong>Nuestras Restaurantes:</strong></p>
          <% @restaurantes.each do |rest| %>
           <li><strong><%= rest.nombre %></strong></li>
          <% end %>
        </br>
        <p><span class="label notice">Datos</span>Si desea ver mayor información de click en los Iconos Rojos.:</p>
        
      </div>
    </div>
  </div>
</body>
</html>

app/views/rests/new.html.erb
.<br></br>
<h1>Nuevo restaurante</h1>
<%= form_for(@restaurantes) do |f| %>
<table>
    <tr>
        <td>Restaurante:</td>
		<td><%= f.text_field :nombre %></td>
	</tr>
    <tr>
        <td>Dirección:</td>
		<td><%= f.text_field :direccion %></td>
	</tr>
    <tr>
        <td>Longitud:</td>
		<td><%= f.text_field :lat %></td>
	</tr>
    <tr>
        <td>Latitud:</td>
		<td><%= f.text_field :lng %></td>
	</tr>
	<tr>
		<td colspan='2' align='center' ><%= f.submit 'Guardar' %></td>
	</tr>
<% end %>

app/views/rests/show.html.erb
<br></br>
<strong>Listado de Restaurantes</strong>
<br></br>
<table border ='1'>
<tr align='center'>
 <td><B> Nombre </B></td>
 <td><B> Dirección </B></td>
 <td><B> Longitud </B></td>
 <td><B> Latitud </B></td>
</tr>
<% @restaurantes.each do |rest| %>
<tr>
 <td><%= rest.nombre %> </td>
 <td> <%= rest.direccion  %></td>
 <td> <%= rest.lat  %></td>
 <td> <%= rest.lng  %></td>
</tr>
<% end %>
</table>
<br></br>
<%= link_to 'Back', rests_path %>

app/views/rests/update.html.erb
<h1>Rests#update</h1>
<p>Find me in app/views/rests/update.html.erb</p>